### ISSUE TITLE
Prepare Home Page

### ISSUE THREAD

**Issue by samuelbarata** [SET-IST/website#85]
- [x] Change event dates (24-27 Feb)
- [x] Hide Activities Page
- [x] Hide Team Members Page
- [x] Hide Companies from main page
- [x] "Automate" these tasks by using variables

**Comment by sandr-castilho** [comment]
NEXT_PUBLIC_... env variables are only set in at compile time.

**Comment by samuelbarata** [comment]
Fixed in #93

**Comment by samuelbarata** [comment]
@sandr-castilho, no mobile as paginas ainda aparecem
![image](https://github.com/user-attachments/assets/bafbddb1-8dab-4438-929e-5c00a4b99166)
